### ISSUE TITLE
针对新版本 diffusers 和 huggingface_hub 版本兼容性是否存在问题

### ISSUE THREAD

**Issue by quazzblapp1** [antgroup/echomimic#207]
Traceback (most recent call last):
  File "/content/drive/MyDrive/Colab Notebooks/echomimic-main/infer_audio2vid.py", line 21, in <module>
    from diffusers import AutoencoderKL, DDIMScheduler
  File "/usr/local/lib/python3.10/dist-packages/diffusers/__init__.py", line 5, in <module>
    from .utils import (
  File "/usr/local/lib/python3.10/dist-packages/diffusers/utils/__init__.py", line 38, in <module>
    from .dynamic_modules_utils import get_class_from_dynamic_module
  File "/usr/local/lib/python3.10/dist-packages/diffusers/utils/dynamic_modules_utils.py", line 28, in <module>
    from huggingface_hub import HfFolder, cached_download, hf_hub_download, model_info
ImportError: cannot import name 'cached_download' from 'huggingface_hub' (/usr/local/lib/python3.10/dist-packages/huggingface_hub/__init__.py)

**Comment by thundax-lyp** [comment]
> Traceback (most recent call last): File "/content/drive/MyDrive/Colab Notebooks/echomimic-main/infer_audio2vid.py", line 21, in from diffusers import AutoencoderKL, DDIMScheduler File "/usr/local/lib/python3.10/dist-packages/diffusers/**init**.py", line 5, in from .utils import ( File "/usr/local/lib/python3.10/dist-packages/diffusers/utils/**init**.py", line 38, in from .dynamic_modules_utils import get_class_from_dynamic_module File "/usr/local/lib/python3.10/dist-packages/diffusers/utils/dynamic_modules_utils.py", line 28, in from huggingface_hub import HfFolder, cached_download, hf_hub_download, model_info ImportError: cannot import name 'cached_download' from 'huggingface_hub' (/usr/local/lib/python3.10/dist-packages/huggingface_hub/**init**.py)

降 huggingface_hub 版本

**Comment by AuYuHui** [comment]
> > Traceback (most recent call last): File "/content/drive/MyDrive/Colab Notebooks/echomimic-main/infer_audio2vid.py", line 21, in from diffusers import AutoencoderKL, DDIMScheduler File "/usr/local/lib/python3.10/dist-packages/diffusers/**init**.py", line 5, in from .utils import ( File "/usr/local/lib/python3.10/dist-packages/diffusers/utils/**init**.py", line 38, in from .dynamic_modules_utils import get_class_from_dynamic_module File "/usr/local/lib/python3.10/dist-packages/diffusers/utils/dynamic_modules_utils.py", line 28, in from huggingface_hub import HfFolder, cached_download, hf_hub_download, model_info ImportError: cannot import name 'cached_download' from 'huggingface_hub' (/usr/local/lib/python3.10/dist-packages/huggingface_hub/**init**.py)
> 
> 降 huggingface_hub 版本

降低到什么版本？
